#!/usr/bin/env bash
dir="$(dirname "$0")"
exec "$dir/../../../../../host/lib/ld-linux-x86-64.so.2" --library-path "$dir/../../../../../host/lib/" "$dir/../../../../../host/lib/runas" "$dir/.cc1.bin" "$0" "$@"
